spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/ss_shot_db}
    username: ${DATABASE_USERNAME:ss_shot_user}
    password: ${DATABASE_PASSWORD:ss_shot_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
